### ISSUE TITLE
Pull iom image failed due to naming mismatch

### ISSUE THREAD

**Issue by JKlepzig** [intershop/iom-blueprint-project#23]
**Actual Behavior**

Pulling the iom image while creating the cluster does not work since the version of the project defined in the pom.xml (1.0.0) does not match the expected version in IOM_IMAGE in devenv.project.properties (1.0.0-SNAPSHOT)

**Work around:** 

Add the following line to the file devenv.user.properties:
IOM_IMAGE=docker.io/library/iom-blueprint-project-iom:1.0.0

**Comment by jlistemann-ish** [comment]
fixed with 1.0.1 #25
