### ISSUE TITLE
4.2 migration - expanded enums

### ISSUE THREAD

**Issue by Philipp-Borchert-ISH** [intershop/iom-blueprint-project#61]
Migration topic after IOM 4.2 release

- change ExpandedEnum classes as described in the migration guide
- update cookbooks (e.g. "Cookbook - Customization", "Cookbook - Custom File Export" etc) to use the new annotation "ExpandedEnum" instead of "PersistedEnumerationTable"

[AB#78965](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78965)

**Comment by jlistemann-ish** [comment]
Migration already done.
Will create separate document ticket in ADO.
